describe('Menguji fitur pengajuan formulir', () => {
    // Data Login User
    const username = 'andimushawwir@gmail.com';
    const password = '123456';

    // Data Formulir
    const namaPasien = 'Andi Dashataran';
    const kecamatan = 'Blimbing';
    const kelurahan = 'Polowijen';
    const kota = 'Malang';
    const alamatRumah = 'Jalan Cakalang Indah 1';
    const rumahSakit = 'Lavalette';
    const nomorOrangtua = '0852676353';
    const email = 'andimushawwir@gmail.com';
    const nomorHp = '085298853452';
    const tanggalPermintaan = '2022-11-29T06:10';


    it('Form Inputan Terisi Sempurna', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Semua Form Inputan Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click() 
        cy.get('.btn').click()
    })

    it('Field Nama Pasien Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)
        cy.get('.btn').click({ force: true })
    })

    it('Field Kecamatan Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Kelurahan Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Kota Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Alamat Rumah Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Rumah Sakit Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Nomor Orangtua/Wali Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Email Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Nomor Handphone Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get('#datetimepicker').type(tanggalPermintaan)    
        cy.get('.btn').click({ force: true })
    })

    it('Field Tanggal Permintaan Tidak Terisi', () => {
        cy.visit('http://localhost:8000/')
        cy.visit('http://localhost:8000/login')
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(username)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get(':nth-child(5) > a').click()
        cy.get(':nth-child(2) > .form-control').type(namaPasien)
        cy.get('select').select('B +').should('have.value', 'B +')
        cy.get(':nth-child(5) > .form-control').type(kelurahan)
        cy.get(':nth-child(4) > .form-control').type(kecamatan)
        cy.get(':nth-child(6) > .form-control').type(kota)
        cy.get(':nth-child(7) > .form-control').type(alamatRumah)
        cy.get(':nth-child(8) > .form-control').type(rumahSakit)
        cy.get(':nth-child(9) > .form-control').type(nomorOrangtua)
        cy.get(':nth-child(10) > .form-control').type(email)
        cy.get(':nth-child(11) > .form-control').type(nomorHp)
        cy.get('.btn').click({ force: true })
    })
})